#!/bin/sh

ID="$1"
if echo "$ID" | grep icefilms; then
	ID="`echo "$ID" | cut -d= -f2 | cut -d';' -f1`"
fi

curl -s http://www.icefilms.info/membersonly/components/com_iceplayer/video.php?vid=$ID | ruby -rnokogiri -e '
Nokogiri::parse(STDIN.read).at("#srclist").search(".ripdiv").each do |el|
	puts el.at("b").inner_html # section title
	el.search("a").each do |a|
		puts "#{ARGV[0]} #{a.attributes["onclick"].to_s.scan(/\d+/)[0]}"
	end
end
' $ID
