#!/bin/sh

# This script takes a show ID (which has two parts for some reason) and lists the IDs of the episodes
show_id="$1"

episode_list_url="http://www.icefilms.info/tv/series/$show_id"

episode_list="$(curl -s "$episode_list_url")"

echo "$episode_list" | ruby -rnokogiri  -e '
Nokogiri::parse(STDIN.read).at("span.list").search("a").each do |item|
	if item["href"]
		id = item["href"].sub(/[^0-9]*([0-9]+).*/,"\\1")
		# Use to_i to only accept the numeric ids
		puts id + " " + item.content if id.to_i != 0
	end
end
'
