#!/bin/sh

DOWNLOAD_RB='
f = Nokogiri::parse(STDIN.read).at("form[name=frm]")
def f.method_missing(att)
	self.at("input[name=#{att}]").attributes["value"]
end

puts "id=#{ARGV[1]}&s=120&iqs=#{f.iqs}&url=#{f.url}&m=-35&cap=&sec=37fn8Oklq&t=#{ARGV[0]}"
'

POSTDATA="`curl -s http://www.icefilms.info/membersonly/components/com_iceplayer/video.php?vid=$1 | ruby -rnokogiri -e"$DOWNLOAD_RB" $1 $2`"
MEGAUPLOAD="`curl -s http://www.icefilms.info/membersonly/components/com_iceplayer/video.phpAjaxResp.php -d "$POSTDATA" | cut -d= -f2- | cut -d'&' -f1 | ruby -rcgi -e 'puts CGI::unescape(gets)'`"
MEGAUPLOAD_PAGE="`curl -s "$MEGAUPLOAD"`"

TIMEOUT="`echo "$MEGAUPLOAD_PAGE" | grep 'count=\d*' | cut -d= -f2 | cut -d';' -f1`"
while [ $TIMEOUT -gt 0 ]; do
	printf "\r%02d" $TIMEOUT
	sleep 1
	TIMEOUT="$(( $TIMEOUT - 1 ))"
done

echo
echo "$MEGAUPLOAD_PAGE" | ruby -rnokogiri -e 'puts Nokogiri::parse(STDIN.read).at("#dlbutton")["href"]'
